N1 = 10 # ----- parametro indicatore channel length
N2 = 21 # ----- parametro indicatore average length
SYMBOL = "XAUUSD" # ----- simbolo stock
TIMEFRAME = "15m" # ----- timeframe
N_OPERAZIONI = 1 # ----- numero di operazioni da aprire quando arriva il signal
RISCHIO = 0.5 # capitale ----- di rischio per ogni operazione
STOPLOSS = 30 # ----- pips di stop loss iniziale
SPOSTAMENTO_STOPLOSS = 30 # ----- quando il prezzo sale di 60 pips sposto il take profit di 30 pips
BREAK_EVEN = 15 # ----- quando il prezzo sale di 15 pips metto a brake even